create table public.profiles (
  id bigint generated by default as identity not null,
  user_id uuid not null default auth.uid(),
  player_name character varying,
  created_at timestamp with time zone not null default now()
);

alter table "public"."profiles" enable row level security;

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";
alter table "public"."profiles" add constraint "profiles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;
alter table "public"."profiles" validate constraint "profiles_user_id_fkey";

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = user_id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = user_id );

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles (user_id)
  values (new.id::uuid);
  return new;
end;
$function$;


create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Ensure users can only write to whitelisted fields
REVOKE INSERT ON profiles FROM public, anon, authenticated;
GRANT INSERT (player_name) ON profiles TO authenticated;

REVOKE UPDATE ON profiles FROM public, anon, authenticated;
GRANT UPDATE (player_name) ON profiles TO authenticated;