-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.games
(
    id character varying COLLATE pg_catalog."default" NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT games_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.games
    OWNER to postgres;

GRANT ALL ON TABLE public.games TO anon;

GRANT ALL ON TABLE public.games TO authenticated;

GRANT ALL ON TABLE public.games TO postgres;

GRANT ALL ON TABLE public.games TO service_role;

COMMENT ON TABLE public.games
    IS 'List of games available on Explorers Club';

CREATE TABLE IF NOT EXISTS public.game_instances
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    host_user_id uuid NOT NULL,
    game_id character varying COLLATE pg_catalog."default",
    starting_at timestamp with time zone,
    started_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT game_instances_pkey PRIMARY KEY (id),
    CONSTRAINT game_instances_game_id_fkey FOREIGN KEY (game_id)
        REFERENCES public.games (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT game_instances_host_user_id_fkey FOREIGN KEY (host_user_id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.game_instances
    OWNER to postgres;

ALTER TABLE IF EXISTS public.game_instances
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.game_instances TO anon;

GRANT ALL ON TABLE public.game_instances TO authenticated;

GRANT ALL ON TABLE public.game_instances TO postgres;

GRANT ALL ON TABLE public.game_instances TO service_role;

COMMENT ON TABLE public.game_instances
    IS 'Holds information about an instance of game can be played';
