/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Body: THREE.Mesh;
    Hat: THREE.Mesh;
    Body002: THREE.Mesh;
    Hat002: THREE.Mesh;
    Body003: THREE.Mesh;
    Hat003: THREE.Mesh;
    Body004: THREE.Mesh;
    Hat004: THREE.Mesh;
    Body005: THREE.Mesh;
    Hat005: THREE.Mesh;
    Body006: THREE.Mesh;
    Hat006: THREE.Mesh;
    Body007: THREE.Mesh;
    Hat007: THREE.Mesh;
    Body008: THREE.Mesh;
    Hat008: THREE.Mesh;
    Wall_2: THREE.Mesh;
    Wall: THREE.Mesh;
    Base003: THREE.Mesh;
    Base005: THREE.Mesh;
    Base001: THREE.Mesh;
    Base_Roof: THREE.Mesh;
    Base_roof_2: THREE.Mesh;
    Base_roof_2001: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube005: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube007: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube008: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube010: THREE.Mesh;
    Cube011: THREE.Mesh;
    Cube012: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube: THREE.Mesh;
    Cube015: THREE.Mesh;
    Mask_1: THREE.Mesh;
    Mask_3: THREE.Mesh;
    Mask_2: THREE.Mesh;
    Cube016: THREE.Mesh;
    Cube017: THREE.Mesh;
    Cube020: THREE.Mesh;
    Cylinder016: THREE.Mesh;
    Cylinder017: THREE.Mesh;
    Cylinder018: THREE.Mesh;
    Cube021: THREE.Mesh;
    Cube022: THREE.Mesh;
    Cube023: THREE.Mesh;
    Cube030: THREE.Mesh;
    Cube024: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube018: THREE.Mesh;
    Cube019: THREE.Mesh;
    Cube014: THREE.Mesh;
    Fire: THREE.Mesh;
    Baranda001: THREE.Mesh;
    Baranda003: THREE.Mesh;
    Baranda004: THREE.Mesh;
    Baranda005: THREE.Mesh;
    Baranda006: THREE.Mesh;
    Tarima: THREE.Mesh;
    Baranda002: THREE.Mesh;
    Rope: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    Cylinder003: THREE.Mesh;
    Cylinder004: THREE.Mesh;
    Cylinder005: THREE.Mesh;
    Cylinder006: THREE.Mesh;
    Cylinder007: THREE.Mesh;
    Cylinder008: THREE.Mesh;
    Cylinder009: THREE.Mesh;
    Cylinder010: THREE.Mesh;
    Cylinder011: THREE.Mesh;
    Cylinder012: THREE.Mesh;
    Cylinder013: THREE.Mesh;
    Cylinder014: THREE.Mesh;
    Cylinder015: THREE.Mesh;
    Plane: THREE.Mesh;
    Plane002: THREE.Mesh;
    Plane003: THREE.Mesh;
    Plane004: THREE.Mesh;
    Cube025: THREE.Mesh;
    Cube026: THREE.Mesh;
    Cube027: THREE.Mesh;
    Cube028: THREE.Mesh;
    Cube029: THREE.Mesh;
    Text: THREE.Mesh;
    Cylinder021: THREE.Mesh;
    Plane001: THREE.Mesh;
    Cylinder020: THREE.Mesh;
    Cylinder019: THREE.Mesh;
    Cylinder022: THREE.Mesh;
    Cylinder023: THREE.Mesh;
    Cylinder024: THREE.Mesh;
    Cylinder025: THREE.Mesh;
    Cylinder026: THREE.Mesh;
    Cylinder027: THREE.Mesh;
    Cylinder028: THREE.Mesh;
    Cylinder029: THREE.Mesh;
    Cylinder030: THREE.Mesh;
    Cylinder031: THREE.Mesh;
    Cylinder032: THREE.Mesh;
    Cylinder033: THREE.Mesh;
    Cylinder034: THREE.Mesh;
    Cylinder035: THREE.Mesh;
    Cylinder036: THREE.Mesh;
    Cylinder037: THREE.Mesh;
    Cylinder040: THREE.Mesh;
    Cylinder042: THREE.Mesh;
    Cylinder045: THREE.Mesh;
    Text001: THREE.Mesh;
    Cylinder038: THREE.Mesh;
    Cylinder039: THREE.Mesh;
    Bone: THREE.Bone;
    Bone006: THREE.Bone;
    Bone013: THREE.Bone;
    Bone_1: THREE.Bone;
    Bone006_1: THREE.Bone;
    Bone013_1: THREE.Bone;
    Bone_2: THREE.Bone;
    Bone006_2: THREE.Bone;
    Bone013_2: THREE.Bone;
    Bone_3: THREE.Bone;
    Bone006_3: THREE.Bone;
    Bone013_3: THREE.Bone;
    Bone_4: THREE.Bone;
    Bone006_4: THREE.Bone;
    Bone013_4: THREE.Bone;
    Bone_5: THREE.Bone;
    Bone006_5: THREE.Bone;
    Bone013_5: THREE.Bone;
    Bone_6: THREE.Bone;
    Bone006_6: THREE.Bone;
    Bone013_6: THREE.Bone;
    Bone_7: THREE.Bone;
    Bone006_7: THREE.Bone;
    Bone013_7: THREE.Bone;
  };
  materials: {
    Coco: THREE.MeshStandardMaterial;
    ['Coco 7']: THREE.MeshStandardMaterial;
    ['Coco 2']: THREE.MeshStandardMaterial;
    ['Coco 4']: THREE.MeshStandardMaterial;
    ['Coco 5']: THREE.MeshStandardMaterial;
    ['Coco 6']: THREE.MeshStandardMaterial;
    ['Coco 3']: THREE.MeshStandardMaterial;
    ['Coco 8']: THREE.MeshStandardMaterial;
    Base: THREE.MeshStandardMaterial;
    ['Roof and stage']: THREE.MeshStandardMaterial;
    ['Mesas ']: THREE.MeshStandardMaterial;
    ['Barrel and mask']: THREE.MeshStandardMaterial;
    ['Bar and leaders']: THREE.MeshStandardMaterial;
    Drinks: THREE.MeshStandardMaterial;
  };
};

export function Treehouse(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    './assets/tree_house.glb'
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.79, 1.92, 0.57]}
        rotation={[0, 0.44, 0]}
        scale={0.37}
      >
        <primitive object={nodes.Bone} />
        <primitive object={nodes.Bone006} />
        <primitive object={nodes.Bone013} />
        <mesh
          geometry={nodes.Body.geometry}
          material={materials.Coco}
          position={[0, -1.17, 0]}
          scale={2.37}
        />
        <mesh
          geometry={nodes.Hat.geometry}
          material={materials.Coco}
          position={[0, -1.17, 0]}
          scale={2.37}
        />
      </group>
      <group
        position={[-1.14, 2.03, 2.63]}
        rotation={[-Math.PI, 1.09, -Math.PI]}
        scale={0.37}
      >
        <primitive object={nodes.Bone_1} />
        <primitive object={nodes.Bone006_1} />
        <primitive object={nodes.Bone013_1} />
        <mesh
          geometry={nodes.Body002.geometry}
          material={materials['Coco 7']}
          position={[0, -1.17, 0]}
          scale={2.37}
        />
        <mesh
          geometry={nodes.Hat002.geometry}
          material={materials['Coco 7']}
          position={[0, -1.17, 0]}
          scale={2.37}
        />
      </group>
      <group
        position={[-8.69, 1.67, 6.11]}
        rotation={[0, -0.27, 0]}
        scale={0.37}
      >
        <primitive object={nodes.Bone_2} />
        <primitive object={nodes.Bone006_2} />
        <primitive object={nodes.Bone013_2} />
        <mesh
          geometry={nodes.Body003.geometry}
          material={materials['Coco 2']}
          position={[0, -1.17, 0]}
          scale={2.37}
        />
        <mesh
          geometry={nodes.Hat003.geometry}
          material={materials['Coco 2']}
          position={[0, -1.17, 0]}
          scale={2.37}
        />
      </group>
      <group
        position={[-4.18, 1.97, 3.95]}
        rotation={[0, 0.69, 0]}
        scale={0.37}
      >
        <primitive object={nodes.Bone_3} />
        <primitive object={nodes.Bone006_3} />
        <primitive object={nodes.Bone013_3} />
        <mesh
          geometry={nodes.Body004.geometry}
          material={materials['Coco 4']}
          position={[0, -1.17, 0]}
          scale={2.37}
        />
        <mesh
          geometry={nodes.Hat004.geometry}
          material={materials['Coco 4']}
          position={[0, -1.17, 0]}
          scale={2.37}
        />
      </group>
      <group
        position={[-4.22, 2.03, 5.74]}
        rotation={[-Math.PI, 0.96, -Math.PI]}
        scale={0.37}
      >
        <primitive object={nodes.Bone_4} />
        <primitive object={nodes.Bone006_4} />
        <primitive object={nodes.Bone013_4} />
        <mesh
          geometry={nodes.Body005.geometry}
          material={materials['Coco 5']}
          position={[0, -1.17, 0]}
          scale={2.37}
        />
        <mesh
          geometry={nodes.Hat005.geometry}
          material={materials['Coco 5']}
          position={[0, -1.17, 0]}
          scale={2.37}
        />
      </group>
      <group
        position={[-2.22, 2.03, 5.86]}
        rotation={[Math.PI, -0.75, Math.PI]}
        scale={0.37}
      >
        <primitive object={nodes.Bone_5} />
        <primitive object={nodes.Bone006_5} />
        <primitive object={nodes.Bone013_5} />
        <mesh
          geometry={nodes.Body006.geometry}
          material={materials['Coco 6']}
          position={[0, -1.17, 0]}
          scale={2.37}
        />
        <mesh
          geometry={nodes.Hat006.geometry}
          material={materials['Coco 6']}
          position={[0, -1.17, 0]}
          scale={2.37}
        />
      </group>
      <group
        position={[-5.71, 1.97, -0.57]}
        rotation={[0, 1.13, 0]}
        scale={0.37}
      >
        <primitive object={nodes.Bone_6} />
        <primitive object={nodes.Bone006_6} />
        <primitive object={nodes.Bone013_6} />
        <mesh
          geometry={nodes.Body007.geometry}
          material={materials['Coco 3']}
          position={[0, -1.17, 0]}
          scale={2.37}
        />
        <mesh
          geometry={nodes.Hat007.geometry}
          material={materials['Coco 3']}
          position={[0, -1.17, 0]}
          scale={2.37}
        />
      </group>
      <group
        position={[-8.32, 2.67, 1.49]}
        rotation={[0, 0.72, 0]}
        scale={0.37}
      >
        <primitive object={nodes.Bone_7} />
        <primitive object={nodes.Bone006_7} />
        <primitive object={nodes.Bone013_7} />
        <mesh
          geometry={nodes.Body008.geometry}
          material={materials['Coco 8']}
          position={[0, -1.17, 0]}
          scale={2.37}
        />
        <mesh
          geometry={nodes.Hat008.geometry}
          material={materials['Coco 8']}
          position={[0, -1.17, 0]}
          scale={2.37}
        />
      </group>
      <mesh
        geometry={nodes.Wall_2.geometry}
        material={materials.Base}
        position={[6.85, 3.44, 1.5]}
      />
      <mesh
        geometry={nodes.Wall.geometry}
        material={materials.Base}
        position={[-0.15, 4.29, -3.85]}
      />
      <mesh
        geometry={nodes.Base003.geometry}
        material={materials.Base}
        position={[-0.09, 0.78, 1.67]}
      />
      <mesh
        geometry={nodes.Base005.geometry}
        material={materials.Base}
        position={[-10.03, 1.1, 1.5]}
      />
      <mesh
        geometry={nodes.Base001.geometry}
        material={materials.Base}
        position={[-2.99, 0.33, 1.5]}
      />
      <mesh
        geometry={nodes.Base_Roof.geometry}
        material={materials['Roof and stage']}
        position={[6.85, 6.13, 1.52]}
      />
      <mesh
        geometry={nodes.Base_roof_2.geometry}
        material={materials['Roof and stage']}
        position={[-0.45, 7.77, -3.88]}
      />
      <mesh
        geometry={nodes.Base_roof_2001.geometry}
        material={materials['Roof and stage']}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials['Mesas ']}
        position={[-4.31, 1.22, -0.15]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials['Mesas ']}
        position={[-4.18, 1.17, -1.51]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials['Mesas ']}
        position={[-4.56, 1.16, 1.55]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials['Mesas ']}
        position={[-6.14, 1.16, -0.69]}
        rotation={[0, -0.72, 0]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials['Mesas ']}
        position={[-0.21, 1.22, 1.68]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials['Mesas ']}
        position={[-1, 1.17, 0.19]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials['Mesas ']}
        position={[0.49, 1.16, 3.25]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials['Mesas ']}
        position={[-1.46, 1.16, 2.8]}
        rotation={[0, -0.24, 0]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials['Mesas ']}
        position={[-3.3, 1.22, 4.66]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials['Mesas ']}
        position={[-4.27, 1.17, 3.7]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials['Mesas ']}
        position={[-2.03, 1.16, 6.18]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials['Mesas ']}
        position={[-4.52, 1.16, 6.05]}
        rotation={[0, -0.25, 0]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials['Roof and stage']}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials['Roof and stage']}
        position={[6.57, 4.94, 7.12]}
      />
      <mesh
        geometry={nodes.Mask_1.geometry}
        material={materials['Barrel and mask']}
        position={[4.14, 4.75, -3.55]}
      />
      <mesh
        geometry={nodes.Mask_3.geometry}
        material={materials['Barrel and mask']}
        position={[-4.95, 3.02, -3.57]}
      />
      <mesh
        geometry={nodes.Mask_2.geometry}
        material={materials['Barrel and mask']}
        position={[-4.72, 5.59, -3.31]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials['Bar and leaders']}
        position={[-9.58, 3.59, -2.91]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={materials['Bar and leaders']}
        position={[-9.59, 2.05, -0.86]}
      />
      <mesh
        geometry={nodes.Cube020.geometry}
        material={materials['Bar and leaders']}
        position={[-9.58, 2.9, -0.87]}
      />
      <mesh
        geometry={nodes.Cylinder016.geometry}
        material={materials['Bar and leaders']}
        position={[-10.5, 2.27, 1.43]}
      />
      <mesh
        geometry={nodes.Cylinder017.geometry}
        material={materials['Bar and leaders']}
        position={[-9.65, 2.27, 1.43]}
      />
      <mesh
        geometry={nodes.Cylinder018.geometry}
        material={materials['Bar and leaders']}
        position={[-8.65, 2.27, 1.43]}
      />
      <mesh
        geometry={nodes.Cube021.geometry}
        material={materials['Bar and leaders']}
        position={[-9.58, 5.43, -1.65]}
      />
      <mesh
        geometry={nodes.Cube022.geometry}
        material={materials['Bar and leaders']}
        position={[-11.2, 4.06, -0.74]}
      />
      <mesh
        geometry={nodes.Cube023.geometry}
        material={materials['Bar and leaders']}
        position={[-7.93, 4.14, -0.39]}
      />
      <mesh
        geometry={nodes.Cube030.geometry}
        material={materials['Bar and leaders']}
        position={[-9.58, 3.82, -2.72]}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={materials['Bar and leaders']}
        position={[-9.58, 6.38, -2.67]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials['Barrel and mask']}
        position={[-1.02, 1.94, -2.59]}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials['Barrel and mask']}
        position={[-1.02, 1.94, -2.59]}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={materials['Barrel and mask']}
        position={[-1.02, 1.94, -2.59]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials['Barrel and mask']}
        position={[-1.02, 1.94, -2.59]}
      />
      <mesh
        geometry={nodes.Fire.geometry}
        material={materials['Barrel and mask']}
        position={[-1.29, 1.93, -2.34]}
      />
      <mesh
        geometry={nodes.Baranda001.geometry}
        material={materials['Barrel and mask']}
        position={[-1.43, 1.6, -2.44]}
      />
      <mesh
        geometry={nodes.Baranda003.geometry}
        material={materials['Barrel and mask']}
        position={[-0.76, 1.6, -2.64]}
      />
      <mesh
        geometry={nodes.Baranda004.geometry}
        material={materials['Barrel and mask']}
        position={[-1.04, 1.6, -2.48]}
      />
      <mesh
        geometry={nodes.Baranda005.geometry}
        material={materials['Barrel and mask']}
        position={[-0.45, 1.6, -2.36]}
      />
      <mesh
        geometry={nodes.Baranda006.geometry}
        material={materials['Barrel and mask']}
        position={[-0.96, 1.6, -2.2]}
      />
      <mesh
        geometry={nodes.Tarima.geometry}
        material={materials['Roof and stage']}
        position={[3.94, 1.68, 0.8]}
        scale={[1, 1, 1.04]}
      />
      <mesh
        geometry={nodes.Baranda002.geometry}
        material={materials['Roof and stage']}
        position={[-11.28, 1.75, 1.51]}
      />
      <mesh
        geometry={nodes.Rope.geometry}
        material={materials['Roof and stage']}
        position={[-10.03, 1.1, 1.5]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials['Barrel and mask']}
        position={[1.72, 1.59, -2.88]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials['Barrel and mask']}
        position={[1.72, 1.59, -2.88]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials['Barrel and mask']}
        position={[1.72, 1.59, -2.88]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials['Barrel and mask']}
        position={[1.72, 1.59, -2.88]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials['Barrel and mask']}
        position={[-3.11, 1.59, -2.89]}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials['Barrel and mask']}
        position={[-3.11, 1.59, -2.89]}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials['Barrel and mask']}
        position={[-3.11, 1.59, -2.89]}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials['Barrel and mask']}
        position={[-3.11, 1.59, -2.89]}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={materials['Barrel and mask']}
        position={[-11.75, 1.91, 4.27]}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={materials['Barrel and mask']}
        position={[-11.75, 1.91, 4.27]}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={materials['Barrel and mask']}
        position={[-11.75, 1.91, 4.27]}
      />
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={materials['Barrel and mask']}
        position={[-11.75, 1.91, 4.27]}
      />
      <mesh
        geometry={nodes.Cylinder012.geometry}
        material={materials['Barrel and mask']}
        position={[-11.82, 1.91, 5.55]}
      />
      <mesh
        geometry={nodes.Cylinder013.geometry}
        material={materials['Barrel and mask']}
        position={[-11.82, 1.91, 5.55]}
      />
      <mesh
        geometry={nodes.Cylinder014.geometry}
        material={materials['Barrel and mask']}
        position={[-11.82, 1.91, 5.55]}
      />
      <mesh
        geometry={nodes.Cylinder015.geometry}
        material={materials['Barrel and mask']}
        position={[-11.82, 1.91, 5.55]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials['Bar and leaders']}
        position={[-11.17, 7.13, -2.95]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials['Bar and leaders']}
        position={[-9.6, 6.78, -2.92]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials['Bar and leaders']}
        position={[-2.35, 6.5, -3.59]}
      />
      <mesh
        geometry={nodes.Plane004.geometry}
        material={materials['Bar and leaders']}
        position={[0.45, 4.47, -3.59]}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={materials['Bar and leaders']}
        position={[-6.85, 1.07, 5.31]}
      />
      <mesh
        geometry={nodes.Cube026.geometry}
        material={materials['Bar and leaders']}
        position={[-6.79, 1.51, 5.31]}
      />
      <mesh
        geometry={nodes.Cube027.geometry}
        material={materials['Bar and leaders']}
        position={[5.15, 1.49, 5.69]}
      />
      <mesh
        geometry={nodes.Cube028.geometry}
        material={materials['Bar and leaders']}
        position={[5.23, 1.29, 6.67]}
      />
      <mesh
        geometry={nodes.Cube029.geometry}
        material={materials['Bar and leaders']}
        position={[5.12, 2.13, 6.67]}
      />
      <mesh
        geometry={nodes.Text.geometry}
        material={materials['Bar and leaders']}
        position={[-9.42, 6.33, -2.49]}
      />
      <mesh
        geometry={nodes.Cylinder021.geometry}
        material={materials['Bar and leaders']}
        position={[-12.21, 4.35, 6.46]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials['Bar and leaders']}
        position={[0, -0.33, 0]}
      />
      <mesh
        geometry={nodes.Cylinder020.geometry}
        material={materials['Bar and leaders']}
        position={[-12.21, 4.35, -2.92]}
      />
      <mesh
        geometry={nodes.Cylinder019.geometry}
        material={materials.Drinks}
        position={[-0.22, 2.56, 1.18]}
      />
      <mesh
        geometry={nodes.Cylinder022.geometry}
        material={materials.Drinks}
        position={[-0.16, 2.56, 2.3]}
      />
      <mesh
        geometry={nodes.Cylinder023.geometry}
        material={materials.Drinks}
        position={[-4.65, 2.56, -0.37]}
      />
      <mesh
        geometry={nodes.Cylinder024.geometry}
        material={materials.Drinks}
        position={[-4.29, 2.56, 0.45]}
      />
      <mesh
        geometry={nodes.Cylinder025.geometry}
        material={materials.Drinks}
        position={[-3.33, 2.56, 4.06]}
      />
      <mesh
        geometry={nodes.Cylinder026.geometry}
        material={materials.Drinks}
        position={[-3.28, 2.56, 5.17]}
      />
      <mesh
        geometry={nodes.Cylinder027.geometry}
        material={materials.Drinks}
        position={[-10.68, 3.34, -0.72]}
      />
      <mesh
        geometry={nodes.Cylinder028.geometry}
        material={materials.Drinks}
        position={[0.27, 2.61, 1.64]}
      />
      <mesh
        geometry={nodes.Cylinder029.geometry}
        material={materials.Drinks}
        position={[-3.86, 2.61, -0.19]}
      />
      <mesh
        geometry={nodes.Cylinder030.geometry}
        material={materials.Drinks}
        position={[-2.8, 2.61, 4.51]}
      />
      <mesh
        geometry={nodes.Cylinder031.geometry}
        material={materials.Drinks}
        position={[-10.36, 4.82, -2.59]}
      />
      <mesh
        geometry={nodes.Cylinder032.geometry}
        material={materials.Drinks}
        position={[-8.96, 3.77, -2.59]}
      />
      <mesh
        geometry={nodes.Cylinder033.geometry}
        material={materials.Drinks}
        position={[-10.72, 3.79, -2.59]}
      />
      <mesh
        geometry={nodes.Cylinder034.geometry}
        material={materials.Drinks}
        position={[-8.54, 4.74, -2.59]}
      />
      <mesh
        geometry={nodes.Cylinder035.geometry}
        material={materials.Drinks}
        position={[-9.67, 3.34, -0.65]}
      />
      <mesh
        geometry={nodes.Cylinder036.geometry}
        material={materials.Drinks}
        position={[-8.67, 3.34, -0.73]}
      />
      <mesh
        geometry={nodes.Cylinder037.geometry}
        material={materials.Drinks}
        position={[5.11, 5.24, 4.57]}
      />
      <mesh
        geometry={nodes.Cylinder040.geometry}
        material={materials.Drinks}
        position={[5.11, 6.1, -2.76]}
      />
      <mesh
        geometry={nodes.Cylinder042.geometry}
        material={materials.Drinks}
        position={[-6.48, 7.86, -0.98]}
      />
      <mesh
        geometry={nodes.Cylinder045.geometry}
        material={materials.Drinks}
        position={[2.92, 6.31, 1.7]}
      />
      <mesh
        geometry={nodes.Text001.geometry}
        material={materials.Drinks}
        position={[6.65, 3.75, 1.2]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={2.4}
      />
      <mesh
        geometry={nodes.Cylinder038.geometry}
        material={materials.Drinks}
        position={[-12.25, 4.46, 6.46]}
        rotation={[0, 0, -3]}
      />
      <mesh
        geometry={nodes.Cylinder039.geometry}
        material={materials.Drinks}
        position={[-12.25, 4.46, -2.92]}
        rotation={[0, 0, -3]}
      />
    </group>
  );
}

useGLTF.preload('./assets/tree_house.glb');
