/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Erika_Archer_Body_Mesh: THREE.SkinnedMesh;
    Erika_Archer_Clothes_Mesh: THREE.SkinnedMesh;
    Erika_Archer_Eyelashes_Mesh: THREE.SkinnedMesh;
    Erika_Archer_Eyes_Mesh: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
  };
  materials: {
    Akai_MAT: THREE.MeshStandardMaterial;
    eyelash_MAT: THREE.MeshStandardMaterial;
    Body_MAT: THREE.MeshStandardMaterial;
    EyeSpec_MAT: THREE.MeshStandardMaterial;
  };
};

type ActionName =
  | 'Death'
  | 'DrawArrow'
  | 'RunForward'
  | 'StandingIdle'
  | 'TPose';
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Character(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    './assets/character.glb'
  ) as unknown as GLTFResult;
  // const { actions } = useAnimations<GLTFActions>(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="Erika_Archer_Body_Mesh"
            geometry={nodes.Erika_Archer_Body_Mesh.geometry}
            material={materials.Akai_MAT}
            skeleton={nodes.Erika_Archer_Body_Mesh.skeleton}
          />
          <skinnedMesh
            name="Erika_Archer_Clothes_Mesh"
            geometry={nodes.Erika_Archer_Clothes_Mesh.geometry}
            material={materials.eyelash_MAT}
            skeleton={nodes.Erika_Archer_Clothes_Mesh.skeleton}
          />
          <skinnedMesh
            name="Erika_Archer_Eyelashes_Mesh"
            geometry={nodes.Erika_Archer_Eyelashes_Mesh.geometry}
            material={materials.Body_MAT}
            skeleton={nodes.Erika_Archer_Eyelashes_Mesh.skeleton}
          />
          <skinnedMesh
            name="Erika_Archer_Eyes_Mesh"
            geometry={nodes.Erika_Archer_Eyes_Mesh.geometry}
            material={materials.EyeSpec_MAT}
            skeleton={nodes.Erika_Archer_Eyes_Mesh.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('./assets/character.glb');
