/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Palm_81: THREE.Mesh;
  };
  materials: {
    ['World ap']: THREE.MeshPhysicalMaterial;
  };
};

export function PalmTreeModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    './assets/palm_tree.glb'
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 1.58, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Palm_81.geometry}
          material={materials['World ap']}
          rotation={[0.17, 0.31, 2.43]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('./assets/palm_tree.glb');
