/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from '@react-three/drei';
import { RefObject, useEffect } from 'react';
import * as THREE from 'three';
import { TypeOf } from 'zod';
import { useCharacterCustomization } from './character-customization.context';
import { customizationStateTypes, GLTFResult } from './character.types';

interface Props {
  gltf: GLTFResult;
  group: RefObject<THREE.Group>;
}

export function Character({ gltf, group }: Props) {
  const { nodes, materials, animations } = gltf;
  const {
    hairColor,
    setHairColor,
    eyesColor,
    setEyesColor,
    mouthColor,
    setMouthColor,
    glassesColor,
    setGlassesColor,
    skinColor,
    setSkinColor,
    shirtColor,
    setShirtColor,
    pantsColor,
    setPantsColor,
    shoesColor,
    setShoesColor,
    lacesColor,
    setLacesColor,
    soleColor,
    setSoleColor,
    setMorphTargetDictionary,
    morphTargetInfluences,
    setMorphTargetInfluences,
  } = useCharacterCustomization() as customizationStateTypes;

  useEffect(() => {
    setMorphTargetDictionary(
      Object.keys(nodes.Mesh019.morphTargetDictionary as any)
    );
    setMorphTargetInfluences(nodes.Mesh019.morphTargetInfluences);

    setHairColor(`#${materials.Hair.color.getHexString()}`);
    setEyesColor(`#${materials.Eyes.color.getHexString()}`);
    setMouthColor(`#${materials.Mouth.color.getHexString()}`);
    setGlassesColor(`#${materials.Glasses.color.getHexString()}`);
    setSkinColor(`#${materials.Skin.color.getHexString()}`);
    setShirtColor(`#${materials.Shirt.color.getHexString()}`);
    setPantsColor(`#${materials.Pants.color.getHexString()}`);
    setShoesColor(`#${materials.Shoes.color.getHexString()}`);
    setLacesColor(`#${materials.Laces.color.getHexString()}`);
    setSoleColor(`#${materials.Sole.color.getHexString()}`);
  }, []);
  return (
    <group ref={group} dispose={null}>
      <group name="Scene">
        <group
          name="Armature"
          position={[0, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <primitive object={nodes.mixamorigHips} />
          <group name="SM_Chr_Developer_Female_02">
            <skinnedMesh
              frustumCulled={false}
              castShadow
              name="Mesh019"
              geometry={nodes.Mesh019.geometry}
              skeleton={nodes.Mesh019.skeleton}
              morphTargetDictionary={nodes.Mesh019.morphTargetDictionary}
              morphTargetInfluences={morphTargetInfluences}
            >
              <meshStandardMaterial
                {...materials.Glasses}
                color={glassesColor}
              />
            </skinnedMesh>
            <skinnedMesh
              frustumCulled={false}
              castShadow
              name="Mesh019_1"
              geometry={nodes.Mesh019_1.geometry}
              skeleton={nodes.Mesh019_1.skeleton}
              morphTargetDictionary={nodes.Mesh019.morphTargetDictionary}
              morphTargetInfluences={morphTargetInfluences}
            >
              <meshStandardMaterial {...materials.Eyes} color={eyesColor} />
            </skinnedMesh>
            <skinnedMesh
              frustumCulled={false}
              castShadow
              name="Mesh019_2"
              geometry={nodes.Mesh019_2.geometry}
              skeleton={nodes.Mesh019_2.skeleton}
              morphTargetDictionary={nodes.Mesh019.morphTargetDictionary}
              morphTargetInfluences={morphTargetInfluences}
            >
              <meshStandardMaterial {...materials.Hair} color={hairColor} />
            </skinnedMesh>
            <skinnedMesh
              frustumCulled={false}
              castShadow
              name="Mesh019_3"
              geometry={nodes.Mesh019_3.geometry}
              material={materials.Skin}
              skeleton={nodes.Mesh019_3.skeleton}
              morphTargetDictionary={nodes.Mesh019.morphTargetDictionary}
              morphTargetInfluences={morphTargetInfluences}
            >
              <meshStandardMaterial {...materials.Skin} color={skinColor} />
            </skinnedMesh>
            <skinnedMesh
              frustumCulled={false}
              castShadow
              name="Mesh019_4"
              geometry={nodes.Mesh019_4.geometry}
              material={materials.Mouth}
              skeleton={nodes.Mesh019_4.skeleton}
              morphTargetDictionary={nodes.Mesh019.morphTargetDictionary}
              morphTargetInfluences={morphTargetInfluences}
            >
              <meshStandardMaterial {...materials.Mouth} color={mouthColor} />
            </skinnedMesh>
            <skinnedMesh
              frustumCulled={false}
              castShadow
              name="Mesh019_5"
              geometry={nodes.Mesh019_5.geometry}
              skeleton={nodes.Mesh019_5.skeleton}
              morphTargetDictionary={nodes.Mesh019.morphTargetDictionary}
              morphTargetInfluences={morphTargetInfluences}
            >
              <meshStandardMaterial {...materials.Shirt} color={shirtColor} />
            </skinnedMesh>
            <skinnedMesh
              frustumCulled={false}
              castShadow
              name="Mesh019_6"
              geometry={nodes.Mesh019_6.geometry}
              skeleton={nodes.Mesh019_6.skeleton}
              morphTargetDictionary={nodes.Mesh019.morphTargetDictionary}
              morphTargetInfluences={morphTargetInfluences}
            >
              <meshStandardMaterial {...materials.Pants} color={pantsColor} />
            </skinnedMesh>
            <skinnedMesh
              frustumCulled={false}
              castShadow
              name="Mesh019_7"
              geometry={nodes.Mesh019_7.geometry}
              skeleton={nodes.Mesh019_7.skeleton}
              morphTargetDictionary={nodes.Mesh019.morphTargetDictionary}
              morphTargetInfluences={morphTargetInfluences}
            >
              <meshStandardMaterial {...materials.Shoes} color={shoesColor} />
            </skinnedMesh>
            <skinnedMesh
              frustumCulled={false}
              castShadow
              name="Mesh019_8"
              geometry={nodes.Mesh019_8.geometry}
              skeleton={nodes.Mesh019_8.skeleton}
              morphTargetDictionary={nodes.Mesh019.morphTargetDictionary}
              morphTargetInfluences={morphTargetInfluences}
            >
              <meshStandardMaterial {...materials.Sole} color={soleColor} />
            </skinnedMesh>
            <skinnedMesh
              frustumCulled={false}
              castShadow
              name="Mesh019_9"
              geometry={nodes.Mesh019_9.geometry}
              skeleton={nodes.Mesh019_9.skeleton}
              morphTargetDictionary={nodes.Mesh019.morphTargetDictionary}
              morphTargetInfluences={morphTargetInfluences}
            >
              <meshStandardMaterial {...materials.Laces} color={lacesColor} />
            </skinnedMesh>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('./assets/character.glb');
