export const MULTIPLE_ANSWER_SAMPLE_ENTRY_ID = 'AIjeqrvZtwEKBIKsh52zf';
export const MULTIPLE_CHOICE_SAMPLE_ENTRY_ID = '4i85jOSGtY83FpfYfQgQIX';
export const NUMBER_INPUT_SAMPLE_ENTRY_ID = '4gv6QTeHMQGcyUMJRCjKTc';
export const TEXT_INPUT_SAMPLE_ENTRY_ID = '58RBnAq72BALopzRzEcblg';
export const TRUE_OR_FALSE_SAMPLE_ENTRY_ID = '4MH0UfnEzfru9PbmhZ9aJv';
