name: Deploy All to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-room-server:
    runs-on: ubuntu-22.04
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: npm ci
      - run: npx nx run room-server:deploy-production

  # push-database:
  #   runs-on: ubuntu-22.04

  #   env:
  #     SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  #     SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
  #     PRODUCTION_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}
  #     FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: npm ci

  #     - uses: supabase/setup-cli@v1
  #       with:
  #         version: 1.0.0

  #     - run: |
  #         npx nx run database:link --project-ref $PRODUCTION_PROJECT_ID --password $PRODUCTION_DB_PASSWORD
  #         npx nx run database:push
