name: Deploy All to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy-api-server:
    runs-on: ubuntu-22.04
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: npm ci
      - run: npx nx run api-server:deploy-staging

  deploy-room-server:
    runs-on: ubuntu-22.04
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: npm ci
      - run: npx nx run room-server:deploy-staging

  # push-database:
  #   runs-on: ubuntu-22.04

  #   env:
  #     SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  #     SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
  #     STAGING_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: npm ci

  #     - uses: supabase/setup-cli@v1
  #       with:
  #         version: 1.0.0

  #     - run: |
  #         npx nx run database:link --project-ref $STAGING_PROJECT_ID --password $STAGING_DB_PASSWORD
  #         npx nx run database:push
